# User and worker settings
user  nginx;
worker_processes 1;

# Error log settings
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

# Events block for connection settings
events {
    worker_connections 1024;
}

# HTTP block where server block goes
http {
    include       mime.types;
    default_type  application/octet-stream;

    # Log formats and access logs
    access_log  /var/log/nginx/access.log;

    # Gzip settings
    gzip on;
    gzip_types text/plain application/xml text/css application/javascript image/x-icon;

    # Server block configuration
    server {
        listen 80;
        server_name mylive-web.devclouds.site;

        # Root directory for serving static files
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        # Handle 404 error by redirecting to index.html (for single-page apps)
        error_page 404 /index.html;
        location = /index.html {
            root /usr/share/nginx/html;
        }
    }
}
