version: '3.8'

networks:
  web:
    external: true
  internal:
    external: false

services:
  api-backend:
    build:
      context: .  # Use the current directory (Backend) as the build context
      dockerfile: Dockerfile  # Optional, it's the default if named 'Dockerfile'
    restart: always
    container_name: api-backend-prod
    env_file:
      - .env
    labels:
      - "traefik.http.routers.api-backend.rule=Host(`api-backend.devclouds.site`)"
      - "traefik.http.routers.api-backend.tls=true"
      - "traefik.http.routers.api-backend.tls.certresolver=lets-encrypt"
      - "traefik.http.services.api-backend.loadbalancer.server.port=3000"
    networks:
      - web
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data  # Example volume (optional)
