name: CI/CD for Surveyor API

on:
  push:
    branches:
      - main
     
jobs:
  Production-Image:
    runs-on: [self-hosted-india]
    name: Building Production APP
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Docker Compose Version
        run: docker compose --version

      - name: Build Docker image for Production
        run: |
          cd Mjs-fullstack-web/Backend  # Ensure you're in the Backend folder where docker-compose.yml is
          pwd
          ls  # List files to make sure docker-compose.yml is there
          sudo docker compose build api-backend  # Build the image using docker-compose

      - name: Deploy Docker container for Production
        run: |
          cd Mjs-fullstack-web/Backend  # Ensure you're in the Backend folder
          sudo docker compose up -d api-backend  # Start the container in detached mode

      - name: Clean Docker Cache
        run: |
          sudo docker system prune -a -f  # Clean up unused Docker images
