name: CI/CD for Surveyor API

on:
  push:
    branches:
      - main
     
jobs:
  Production-Image:
    runs-on: [self-hosted-india]
    name: Building Production APP
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Current Directory
        run: |
          echo "Current directory: $(pwd)"
          ls -l  # List files to see the structure

      - name: Build Docker image for Backend Production
        run: |
          cd Backend  # Change to the Backend folder (relative to where we are now)
          pwd
          ls  # List files to make sure docker-compose.yml is there
          sudo docker stop api-backend-prod
          sudo docker rm api-backend-prod
          sudo docker system prune -a -f
          sudo docker compose build api-backend  # Build the image using docker-compose
          sudo docker compose up -d api-backend  # Start the container in detached mode

      - name: Deploy Docker container for Frontend Production
        run: |
          cd Frontend  # Change to Frontend folder again (if necessary)
          sudo docker stop mylive-web
          sudo docker rm mylive-web
          sudo docker system prune -a -f
          sudo docker compose build --no-cache mylive-web  
          sudo docker compose up -d mylive-web  

      - name: Clean Docker Cache
        run: |
          sudo docker system prune -a -f  # Clean up unused Docker images
